<?php


	namespace CivicInfoBC\CanadaPost;
	
	
	/**
	 *	Contains constants which describe the different
	 *	services that Canada Post offers.
	 */
	class Service {
	
	
		const REGULAR_PARCEL='DOM.RP';
		const EXPEDITED_PARCEL='DOM.EP';
		const XPRESSPOST='DOM.XP';
		const XPRESSPOST_CERTIFIED='DOM.XP.CERT';
		const PRIORITY='DOM.PC';
		const LIBRARY_BOOKS='DOM.LIB';
		const EXPEDITED_PARCEL_USA='USA.EP';
		const PRIORITY_WORLDWIDE_ENVELOPE_USA='USA.PW.ENV';
		const PRIORITY_WORLDWIDE_PAK_USA='USA.PW.PAK';
		const PRIORITY_WORLDWIDE_PARCEL_USA='USA.PW.PARCEL';
		const SMALL_PACKET_USA_AIR='USA.SP.AIR';
		const TRACKED_PACKET_USA='USA.TP';
		const TRACKED_PACKET_USA_LVM='USA.TP.LVM';
		const XPRESSPOST_USA='USA.XP';
		const XPRESSPOST_INTERNATIONAL='INT.XP';
		const INTERNATIONAL_PARCEL_AIR='INT.IP.AIR';
		const INTERNATIONAL_PARCEL_SURFACE='INT.IP.SURF';
		const PRIORITY_WORLDWIDE_ENVELOPE_INTERNATIONAL='INT.PW.ENV';
		const PRIORITY_WORLDWIDE_PAK_INTERNATIONAL='INT.PW.PAK';
		const PRIORITY_WORLDWIDE_PARCEL_INTERNATIONAL='INT.PW.PARCEL';
		const SMALL_PACKET_INTERNATIONAL_AIR='INT.SP.AIR';
		const SMALL_PACKET_INTERNATIONAL_SURFACE='INT.SP.SURF';
		const TRACKED_PACKET_INTERNATIONAL='INT.TP';
	
	
	}


?>