<?php


	use \CivicInfoBC\HTML as HTML;
	
	
	$arr=$this->results;
	$results=array_shift($arr);
	$this->results=$arr;
	
	
?>


<h2><?php	HTML::Write($results->name);	?></h2>


<table>


	<thead>
	
	
		<tr>
		
			<td>Name</td>
			<td>Description</td>
			<td>Result</td>
			<td>Status</td>
		
		</tr>
	
	
	</thead>
	
	
	<tbody>
	
	
		<?php
		
			$success=0;
			foreach ($results->results as $result):
				if ($result->success) ++$success;
		
		?>
		
		<tr>
		
			<td><?php	HTML::Write($result->name);	?></td>
			<td><?php	HTML::Write($result->description);	?></td>
			<td><code><?php
			
				switch (gettype($result->result)) {
				
					case 'boolean':
						HTML::Write($result->result ? 'true' : 'false');
						break;
					case 'string':
						HTML::Write('"',$result->result,'"');
						break;
					case 'array':
					case 'resource':
					case 'unknown type':
						HTML::Write(gettype($result->result));
						break;
					case 'NULL':
						HTML::Write('null');
						break;
					case 'object':
						HTML::Write(get_class($result->result));
						break;
					default:
						HTML::Write($result->result);
						break;
				
				}
				
			?></code><?php
			
				if ($result->result instanceof \Exception) HTML::Write(' - ',$result->result->getMessage());
				
			?></td>
			<td class="<?php	HTML::Write($result->success ? 'success' : 'failure');	?>"><?php
				HTML::Write($result->success ? 'Success' : 'Failed');
			?></td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	
	</tbody>


</table>


<h3>

	<strong>Total:</strong> <?php	HTML::Write(count($results->results));	?>
	<strong>Succeeded:</strong> <?php	HTML::Write($success);	?> (<?php
		HTML::Write(
			sprintf(
				'%.2f',
				(count($results->results)===0) ? 100 : ((floatval($success)/floatval(count($results->results)))*100)
			),
			'%'
		);
	?>)
	
</h3>